### ISSUE TITLE
Consider updating (some) stack-functions to accept multiple stacks

### ISSUE THREAD

**Issue by mbailey** [bash-my-aws/bash-my-aws#119]
#118 raised the issue of stack-functions not supporting multiple stacks as input

stack-functions were the first one I wrote for bash-my-aws
Functions added later were given the ability to accept multiple resources as input but stack-functions were not updated to get this functionality.

For some functions (e.g. stack-template, stack-parameters, stack-create), it doesn't make sense to work on multiple stacks however stack-tags, stack-resources.
Also, stack names can be long and I'm old school when it comes to terminal widths so prefixing stack-outputs with a stack-name could be bad for readability.

Needs some consideration.

**Comment by jordankueh** [comment]
I've created #121 that has some primitive level of support for iterating over the resources and exports for a stack.

**Comment by mbailey** [comment]
There are two problems with making **all** stack functions accept multiple stacks as piped input:

- some functions are going to be weird with multiple stacks, for example:
  - stack-tail
  - stack-params
  - stack-template

We could just make the functions not accept multiple:syntax enable stacks.
:syntax enable
- some functions require stack-name as first parameter and have additional optional parameters

I'm experimenting with selecting resource ids out based on their format. It works nicely with Amazon resource ids that contain a prefix (e.g. ami-12345678) but not with stack names.

This second problem may be approached by a convention whereby piped resource ids as input
implicitly replaces the first argument.

This would avoid needing to change existing ordering of arguments but would be something for people to learn when piping. Just thought of it tonight - will let it brew.

**Comment by mbailey** [comment]
This has been mostly done.

https://bash-my-aws.org/command-reference/#stack-commands
