### ISSUE TITLE
Unclear comment in IAM functions

### ISSUE THREAD

**Issue by dkw-myob** [bash-my-aws/bash-my-aws#243]
With regard to https://github.com/bash-my-universe/bash-my-aws/blob/master/lib/iam-functions#L8

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html states that identities beginning with `AROA` are IAM Roles, however it does not convey the actual nature of the trust relationship or whether it is broken.

**Comment by mbailey** [comment]
When the friendly name is no longer used, it indicates the trust relationship is broken.

Much like with people! :-)

Happy to receive suggestions for clearer wording.

**Comment by dkw-myob** [comment]
I'd just elaborate on the comment to say exactly that :+1:

**Comment by mbailey** [comment]
Updated
