### ISSUE TITLE
Links to Command Reference don't work when clicked from GitHub readme

### ISSUE THREAD

**Issue by TheRyanBurke** [bash-my-aws/bash-my-aws#251]
readme has links like `See the [Command Reference](command-reference.md) for a full list of commands.` which work from hosted bash-my-aws.org page but break when clicked from the GitHub rendered readme.

**Comment by mbailey** [comment]
Fixed. Thanks for pointing that out!

https://github.com/bash-my-aws/bash-my-aws/commit/f940805cb294f6fed59e202454223a2cb91cd604
