### ISSUE TITLE
Would a FreeBSD Port make any sense?

### ISSUE THREAD

**Issue by duncan-bayne** [bash-my-aws/bash-my-aws#256]
I was thinking of creating (and maintaining) a FreeBSD Port of bash-my-aws, but I'm not sure it makes sense.

A Port would install at a _system_ level.  So it would live somewhere like `/usr/local/share/bash-my-aws`, and you'd add something like the following to `~/.profile`:

```
export PATH="$PATH:/usr/local/share/bash-my-aws/bin"
source /usr/local/share/bash-my-aws/aliases
source /usr/local/share/bash-my-aws/bash_completion.sh
```

But at this point, I sort of question the benefit of a Port in the first place, beyond perhaps increasing visibility and adoption of bash-my-aws among FreeBSD users.

If people (especially @mbailey ;) ) think it's worthwhile, I'm very happy to proceed.  But I'm quite keen to hear opinions first.

**Comment by mbailey** [comment]
People have also suggested adding a HomeBrew recipe but I'm yet to be convinced that would improve the project. (Happy to hear arguments in favour).

The [documented process for installing BMA](https://github.com/bash-my-aws/bash-my-aws#installation) is cloning the repo and adding a few lines to your shell startup file. I've not encountered people having trouble following these steps in training sessions I've run.

An advantage of cloning from Git is that you're setup for development from the get go. The project is intended to be shallow and discoverable. I want people to be able to create their own commands and be using them in less time than it would have taken to click around in the Web Console. It feels like suggesting people install from a package management would add extra steps when they wanted to read the source (and add to it).

**Comment by duncan-bayne** [comment]
Yup, makes sense.  I'll close this issue then.
