### ISSUE TITLE
stack-diff keeps showing a deletion on the last line but no changes on stack-update

### ISSUE THREAD

**Issue by jptechnical** [bash-my-aws/bash-my-aws#302]
First off, thanks for the awesome tool, I use this many times every day!

I am having an issue where the stack-diff doesn't behave like I expect it to. Basically, every diff shows SOME kind of change, even if the template files are unchanged. Maybe that is expected behavior, or I am using it wrong, if so please let me know.

Here are the details. I am currently using Fedora 32 I newly setup this week, as well as my macbook. 

## What I expect

I expect that the running a stack-diff on a stack that has just been created and an unmodified template will result in no diffs. 

## What happens

When I create a stack, and then diff it against the same template, it always shows a deletion at the end of the template file. If I add a blank line to the bottom of the template, then it shows no diffs. 

```bash
~/git/infra-abs $ stack-create params/vpc-params-test.json 
Resolved arguments: vpc-test ./vpc.yml params/vpc-params-test.json
arn:aws:cloudformation:us-east-1:xxx:stack/vpc-test/1b6c1a40-d3cc-11ea-8b1a-0e9af1f797ff
----------------------------------------------------------------------------------------------
|                                     DescribeStackEvents                                    |
+---------------------------+-----------+------------------------------+---------------------+
|  2020-08-01T07:53:37.653Z |  vpc-test |  AWS::CloudFormation::Stack  |  CREATE_IN_PROGRESS |
-----------------------------------------------------------------------------------------------------
|                                        DescribeStackEvents                                        |
+---------------------------+------------------+------------------------------+---------------------+
|  2020-08-01T07:53:37.653Z |  vpc-test        |  AWS::CloudFormation::Stack  |  CREATE_IN_PROGRESS |
```
```bash
~/git/infra-abs $ stack-diff params/vpc-params-test.json 
Resolved arguments: vpc-test ./vpc.yml params/vpc-params-test.json
--- stack
+++ ./vpc.yml
@@ -267,4 +267,3 @@
         - ", "
         - 'PrivateSubnet1:'
         - Ref: PrivateSubnet3
-

Resolved arguments: vpc-test ./vpc.yml params/vpc-params-test.json
params for stack (vpc-test) and contents of file (params/vpc-params-test.json) are the same
```

**Comment by mbailey** [comment]
Thanks for your bug report.

Can you please confirm this fixed it for you?

**Comment by jptechnical** [comment]
Confirmed, stack-diff works as expected. Thank you so much!
