### ISSUE TITLE
How to specify AWS profile?

### ISSUE THREAD

**Issue by maspotts** [bash-my-aws/bash-my-aws#308]
This looks awesome, but I need to be able specify which profile I want (I manage several): it is possible?  ie. I would manually run aws commands with "aws --profile foo" but how do I tell bash-my-aws to use profile foo?  Apologies if this is a stupid question!

**Comment by maspotts** [comment]
Apologies for answering my own question: looks like I can just set AWS_PROFILE in my environment and it all just works.

**Comment by mbailey** [comment]
I’ve not used profiles as my understanding is that it means keeping
credentials in plaintext in a predictable location on my file system.

Thanks for sharing the answer for others it may help.

Mike
