### ISSUE TITLE
Is an --all-regions flag in keeping with bash-my-aws design philosophy?

### ISSUE THREAD

**Issue by duncan-bayne** [bash-my-aws/bash-my-aws#318]
I'm currently bash-my-aws `regions` command to find EC2 instances in all regions:

```
for region in $(regions)
do
  instances --region "$region"
done
```
... but I was wondering whether I should open a PR to add `--all-regions`, which would allow me to replace the above with:
```
instances --all-regions
```

This is technically feasible of course, but is it desirable?  Am I trying to go all [cat -v](http://cat-v.org/) on bash-my-aws?  Need counsel from the BDFL here @mbailey :)

**Comment by ninth-dev** [comment]
Perhaps the `region-each` command could achieve what you need ?

**Comment by duncan-bayne** [comment]
@ninth-dev How did I miss that? :man_facepalming:
