### ISSUE TITLE
Awesome work, does it support route53?

### ISSUE THREAD

**Issue by seitzbg** [bash-my-aws/bash-my-aws#320]
Was looking for something nice that makes adding DNS records to route53 simple vs the rigamarole of creating JSON via awscli. I can write something but would be nice if bash-my-aws did this! (DNS not tied to instances)

**Comment by mbailey** [comment]
The route-53 commands are just for listing.

All commands are listed [in the docs](https://bash-my-aws.org/command-reference/#route53-commands)
