### ISSUE TITLE
list buckets excluding timestamp

### ISSUE THREAD

**Issue by lc-eu2cloud** [bash-my-aws/bash-my-aws#329]
Hello,

I really like the tool. Perhaps this is asking too much, is it possible to add functionality that filters output of "buckets" command similar to --query Buckets[].Name? I noticed in the bma function for "buckets", the query includes both bucket name & creation date. If there's any way to exclude the creation date & just output the bucket name that would be great!

**Comment by mbailey** [comment]
You can do this with:

```
buckets | cut -d' ' -f1
```

You could create an alias with:
```
alias buckets-nameonly="buckets | cut -d' ' -f1"
```

**Comment by lc-eu2cloud** [comment]
Oh awesome thanks! I like this much better than my workaround
